### PR TITLE
Catalan translation

### PR DESCRIPTION
**Pull request by elboletaire**
I still have some work to do, but I preferred to open the PR to avoid others working on something which has been already done.

### CODE REVIEW

**Comment by indutny** [comment]
This is awesome! 😀 I love Catalan language. Thank you for contributing this! Please let me know when to push the merge button :wink:

**Comment by elboletaire** [comment]
I'm still working on it, maybe in a few minutes I add another comment to confirm it. While I'm translating I realized that adding more languages ​​to the app will be painful after adding one or more languages ​​to it if everything needs to be translated into every `vue` file. Are the locales in the `local` folder gonna be used for the entire app translations?

I take the opportunity to comment you a minor detail. I'm respecting every cap-case, bold, and any other detail in the app that I'm finding while translating, but there's one small detail that I think is better in bold than using capital letters. I'm referring to the `extra.allowed.description` in` application.vue`, where you used caps to say` CAN` and` MUST`. I do not know if you mind me changing it to bolds, or if you prefer to stay it in capital letters.

**Comment by indutny** [comment]
@elboletaire sure, let's move everything to `locales` folder if it'll help during future translations 👍 

I think it is a great idea to change caps to bold. That sounds awesome to me!

**Comment by elboletaire** [comment]
Cool! Let me add a new issue for the locales movement. I prefer to finish the catalan translation before moving to anything else :blush: 

As for the bolds change.. I'll do it in an independent commit on this same merge. No need for a new issue to track that IMO.

**Comment by elboletaire** [comment]
I think I have everything tied up, but I may missed something. Can you please confirm I translated everything @indutny?

**Comment by elboletaire** [comment]
Now I think it's all done :sunglasses:

**Comment by indutny** [comment]
Landed in 311c130, thank you!

**Comment by indutny** [comment]
Deploy to derivepass.com . Thank you again!

**Pull request closed without merging**
